"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List

from .people_tag import PeopleTag
from .film_tag import FilmTag
from .starship_tag import StarshipTag
from .vehicle_tag import VehicleTag
from .specie_tag import SpecieTag
from .planet_tag import PlanetTag

class Client(sdkgen.ClientAbstract):
    def __init__(self, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)

    def people(self) -> PeopleTag:
        return PeopleTag(
            self.http_client,
            self.parser
        )

    def film(self) -> FilmTag:
        return FilmTag(
            self.http_client,
            self.parser
        )

    def starship(self) -> StarshipTag:
        return StarshipTag(
            self.http_client,
            self.parser
        )

    def vehicle(self) -> VehicleTag:
        return VehicleTag(
            self.http_client,
            self.parser
        )

    def specie(self) -> SpecieTag:
        return SpecieTag(
            self.http_client,
            self.parser
        )

    def planet(self) -> PlanetTag:
        return PlanetTag(
            self.http_client,
            self.parser
        )



    @staticmethod
    def build():
        return Client("https://swapi.dev/api", sdkgen.Anonymous())

