"""
collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
class Collection(BaseModel):
    count: Optional[int] = Field(default=None, alias="count")
    next: Optional[str] = Field(default=None, alias="next")
    previous: Optional[str] = Field(default=None, alias="previous")
    pass
