"""
film automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
import datetime


# A Film is a single film.
class Film(BaseModel):
    title: Optional[str] = Field(default=None, alias="title")
    episode_id: Optional[int] = Field(default=None, alias="episode_id")
    opening_crawl: Optional[str] = Field(default=None, alias="opening_crawl")
    director: Optional[str] = Field(default=None, alias="director")
    producer: Optional[str] = Field(default=None, alias="producer")
    release_date: Optional[datetime.date] = Field(default=None, alias="release_date")
    species: Optional[List[str]] = Field(default=None, alias="species")
    starships: Optional[List[str]] = Field(default=None, alias="starships")
    vehicles: Optional[List[str]] = Field(default=None, alias="vehicles")
    characters: Optional[List[str]] = Field(default=None, alias="characters")
    planets: Optional[List[str]] = Field(default=None, alias="planets")
    url: Optional[str] = Field(default=None, alias="url")
    created: Optional[datetime.datetime] = Field(default=None, alias="created")
    edited: Optional[datetime.datetime] = Field(default=None, alias="edited")
    pass
