"""
people automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
import datetime


# A People is an individual person or character within the Star Wars universe.
class People(BaseModel):
    name: Optional[str] = Field(default=None, alias="name")
    birth_year: Optional[str] = Field(default=None, alias="birth_year")
    eye_color: Optional[str] = Field(default=None, alias="eye_color")
    gender: Optional[str] = Field(default=None, alias="gender")
    hair_color: Optional[str] = Field(default=None, alias="hair_color")
    height: Optional[str] = Field(default=None, alias="height")
    mass: Optional[str] = Field(default=None, alias="mass")
    skin_color: Optional[str] = Field(default=None, alias="skin_color")
    homeworld: Optional[str] = Field(default=None, alias="homeworld")
    films: Optional[List[str]] = Field(default=None, alias="films")
    species: Optional[List[str]] = Field(default=None, alias="species")
    starships: Optional[List[str]] = Field(default=None, alias="starships")
    vehicles: Optional[List[str]] = Field(default=None, alias="vehicles")
    url: Optional[str] = Field(default=None, alias="url")
    created: Optional[datetime.datetime] = Field(default=None, alias="created")
    edited: Optional[datetime.datetime] = Field(default=None, alias="edited")
    pass
