"""
planet_collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union
from .collection import Collection
from .planet import Planet
class PlanetCollection(Collection):
    results: Optional[List[Planet]] = Field(default=None, alias="results")
    pass
